In [3]:
import numpy as np

In [8]:
arr=np.array([[1,2,3],[4,5,6]])
reshape=arr.reshape((3,2))
print(reshape,arr.reshape)
print(reshape.shape)

[[1 2]
 [3 4]
 [5 6]] <built-in method reshape of numpy.ndarray object at 0x000001914FB6D2F0>
(3, 2)


In [14]:
#indexing
arr=np.array([[1,2,3],[4,5,6]])
print(arr[0][1])
#fancy indexing
idx=[0,1,1]
print(arr[idx])

2
[[1 2 3]
 [4 5 6]
 [4 5 6]]


In [15]:
#slicing
arr=np.array([[1,2,3],[4,5,6]])
print(arr[0:2])

[[1 2 3]
 [4 5 6]]
