In [1]:
import numpy as np

In [7]:
#multi dim array
arr2d=np.array([[1,2,3],[1,3,5],[5,7,9]])
print(arr2d)

print(np.sum(arr2d))

sum_of_col=np.sum(arr2d,axis=0)
print(sum_of_col)
sum_of_row=np.sum(arr2d,axis=1)
print(sum_of_row)

[[1 2 3]
 [1 3 5]
 [5 7 9]]
36
[ 7 12 17]
[ 6  9 21]


In [17]:
arr3d=np.array([[[1,2],[3,5],[5,9]],[[2,3],[1,5],[7,9]]])
print(arr3d,arr3d.shape)
print(arr3d[1,1,1])
print(arr3d[0,2,1])

[[[1 2]
  [3 5]
  [5 9]]

 [[2 3]
  [1 5]
  [7 9]]] (2, 3, 2)
5
9
