In [1]:
import numpy as np

In [2]:
arr=np.array([1,2,3,4])
print(arr,type(arr))

[1 2 3 4] <class 'numpy.ndarray'>


In [5]:
arr1=np.zeros((2,3))
arr2=np.ones((1,1))
print(arr2,arr2.shape)            
print(arr1,arr1.shape)

[[1.]] (1, 1)
[[0. 0. 0.]
 [0. 0. 0.]] (2, 3)


In [6]:
arr=np.array([1,2,3,4])
print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.ndim)

(4,)
4
int64
1
